require("nvim-treesitter.configs").setup({
	auto_install = true,
	highlight = { enable = true },
	sync_install = false,
	autopairs = {
		enable = true,
	},
	indent = { enable = true },
	ensure_installed = {
		"bash",
		"comment",
		"css",
		"gitcommit",
		"git_config",
		"gitignore",
		"go",
		"html",
		"java",
		"javascript",
		"json",
		"jsonc",
		"lua",
		"markdown",
		"markdown_inline",
		"nix",
		"rasi",
		"toml",
		"tsx",
		"typescript",
		"yaml",
	},
	context_commentstring = {
		enable = true,
		enable_autocmd = false,
	},
})
